services:
  - type: web
    name: ing-bank-manager
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
